defaults:
  - user: max_mustermann
  - model: PlanT


exp_folder_name: training
hydra:
  run:
    dir: outputs/${exp_folder_name}/${expname}/${hydra.job.override_dirname}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    config:
      override_dirname:
        exclude_keys:
          - expname
        kv_sep: '='
        item_sep: '_'


lrDecay_epoch: 16


seed: 1234
debug: False
visualize: False
overfit: 0
resume: True
use_caching: False
custom_sampler: False
gpus: 3
trainset_size: 1
benchmark: longest6
carla_map_dir: /home/masterthesis/pos_lane/carla_maps
expname: DEBUG
wandb_name: training_PlanT_${hydra:job.override_dirname}
save_dir: ${hydra:run.dir}

data_dir: ${user.working_dir}/plant/data/PlanT/PlanT_data_3 # Path to the data directory of the first part of the dataset (ending '_1')


